#!/bin/bash
cd ../

# Variables
usrpwd=`pwd`
fn="/tmp/function-tree.txt"
ffn="docs/function-tree.txt"
usr=`whoami`
usrdate=`date -u | cut -c5-19`
cat /dev/null > $fn
cat /dev/null > $ffn

#FUNCTIONS
# Title Box function
function textbox {
titletxtwc=`echo $titletxt | wc -c`
dashlen=`for ((x=1; x<titletxtwc; x++)); do  echo -n "-"; done && echo -e "\n"`
echo -e "$dashlen\n$titletxt\n$dashlen" >> $fn
}

# Recursive search functions
function item.lookup {
 for item in *
  do
   if [[ -d $item ]]; then
    cd $item
    item.lookup
    cd ..
   else
    titletxt="| $item |"
    textbox
    cat $item | grep function | grep -v "#" >> $fn
    fw=`cat $item | grep function | grep -v "#" | wc -l`
    fwc=$[ $fwc + $fw ]
    echo -en "\n" >> $fn
   fi
 done
}

# Recursive search items
function find.item {
i=0
 for item in *
  do
   if [[ -d $item ]]; then
    echo -e "* [$item directory]" >> $fn
    cd $item
    i=$[ $i + 1 ]
    find.item
    cd ..
    i=$[ $i - 1 ]
   else
    wcc=`cat $item | wc -c`
    wcct=$[ $wcct + $wcc ]
    wcw=`cat $item | wc -w`
    wcwt=$[ $wcwt + $wcw ]
    wcl=`cat $item | wc -l`
    wclt=$[ $wclt + $wcl ]
    dashlen=`for ((x=0; x<=$i; x++)); do  echo -n " "; done && echo -e "\n"`
    echo -e "+ ${dashlen}${item}" >> $fn
   fi
 done
}



## TITLE
titletxt="| ULTIMA 2D Information |"
textbox
echo -e "Generated by: $usr\n\ton: $usrdate" >> $fn
echo -e "\n" >> $fn



## SOURCE INFO
titletxt="| List of SOURCED files |"
textbox
#for item in *
# do
#  echo -e "+  $item" >> $fn
#done
find.item
echo -en "\n" >> $fn



## FUNCTION INFO
titletxt="| List of functions in SOURCED |"
textbox
fwc=0
# Function discovery loop
#for item in * 
# do
#   titletxt="| $item |"
#   textbox
#   cat $item | grep function | grep -v "#" >> $fn
#   fw=`cat $item | grep function | grep -v "#" | wc -l`
#   fwc=$[ $fwc + $fw ]
#   echo -en "\n" >> $fn
#done
item.lookup



## FUNCTION TOTALS
titletxt="| Functions: $fwc   Lines: $wclt   Words: $wcwt   Characters: $wcct |"
textbox
mv $fn $ffn

#if [[ $1 == "" ]]; then
# echo "Complete."
#else
# more $ffn
#fi
